#+TITLE: Magnum's Class & Functionality Documentation
#+AUTHOR: Druid

* Magnum
** Description
Magnum is a Podcasting platform, similar to Google Podcasts and Spotify.

** Models:
*** User & History Management:
#+BEGIN_EXAMPLE
+----------------------------+
|            Users           |
|----------------------------|
| ID: Int                    |
| username: String           |
| email: String              |
| password: String           |
| biography: String          |
| status: Enum<Status>       |
| profilePicturePath: String |
+----------------------------+

// Extended documentation of the "User" table -----------------------------
User {
  ID: Int,                    // Unsigned integer as its type.
  username: String,           // Unique username.
  email: String,
  password: String,           // Hashed password.
  biography: String,          // "About me".
  profilePicturePath: String, // Path to the user's profile picture in the server's filesystem.
}

// Extended documentation of the "Preferences" table ----------------------
As the user listens to more and more podcasts of a specific type (e.g. Comedy),
the preferences table will increment the appropriate column so that we can track
the user's preferences and display a tailored experience for the user, i.e. in
their feed.

+-----------------+
| History         |
|-----------------|
| userID: Int     | <--- This joins with the ID column of
| message: String |      the User table.
| time: Date      |
+-----------------+

// Extended documentation of the "History" table --------------------------
- Profile activity.
- Commenting activity.
- Watch history.
- Purchase (subscriptions) history.
#+END_EXAMPLE

**** Description:
The user table defines the model of a user, see /[[#types]["Types"]]/  for a list of available types.

**** Types:
:PROPERTIES:
:CUSTOM_ID: types
:END:
1. Viewers (User).
2. Uploaders (Content creators).
3. Moderators (Admins).

-----

*** Feed & Preferences Management:

#+BEGIN_EXAMPLE
+-------------------+
|    Preferences    |
|-------------------|
| userID: Int       |
| comedy¹: Int      |
| science²: Int     |
| technology³: Int  |
| politics: Int     |
| news: Int         |
| sports: Int       |
| business: Int     |
+-------------------+
#+END_EXAMPLE

-----

*** Podcast & Comment Management:
#+BEGIN_EXAMPLE
+-----------------------------+
| Podcasts                    |
|-----------------------------|
| ID: Int                     |
| subscriptionID: Int         | <-,
| category: Enum<Category>    |   |
| views: Int = 0              |   |
| imagePath: String           |   |
| title: String               |   |
| description: String         |   \,----> This joins with the ID column
| hash: String                |           of the subscription table.
| rating: Int (1..5)          |
| podcasterID: Int            | <----:
+-----------------------------+      :----> This joins with the user ID column
                                            of the user (i.e. podcaster) table.

// Extended documentation of the "Podcast" table --------------------------
- Hash: A podcast's hash is calculated and stored in order
to stop a podcaster from re-uploading the same exact audio file more than once.
- SubscriptionID: If SubscriptionID of the Podcast table is a '0', the podcast is not a part of any subscription,
meaning the podcast is free of charge.

+------------------+
| Comments         |
|------------------|
| userID: Int      | <---- This joins with the ID
| podcastID: Int   | <-,   column of the "User" table.
| replyingTo: Int  |   |
| message: String  |   |
| submitDate: Date |   \,-----> This joins with the ID column of the "Podcast" table.
+------------------+

// Extended documentation of the "Comment" table --------------------------
enum Category {
    Comedy,
    Science,
    Horror,
    Technology,
    etc.
}

- userID: The user ID of the original commenter.
- replyingTo: This points to some user's ID (instead of their username (String),
which could be costly in a giant database). If a comment is not a reply, this column takes a '0'.
#+END_EXAMPLE

-----

*** Playlist Management:
#+BEGIN_EXAMPLE
+---------------------+
| Playlists           |
|---------------------|
| ID: Int             |
| userID: Int         | <-- This joins with ID column of the "User" table.
| name: String        |
| description: String |
| creationDate: Date  |
| podcasts: ID[Int]   | <-- This joins with ID column of the "Podcast" table.
+---------------------+
#+END_EXAMPLE

-----

*** Payment & Subscription Management:
*Podcasters* can monetize their content in the form of subscriptions.

Users may choose to pay a fee to subscribe to them. Based on the tier the user
chooses, they receive access to perks that non-subscribed users may not. The pricing
of these tiers is not regulated by Magnum.

#+BEGIN_EXAMPLE
TODO: Fill this puppy with the appropriate fields.

+------------------------+
|         Payments       |
|------------------------|
|           ...          |
+------------------------+

+------------------+
|  Subscriptions   |
|------------------|
| ID: Int          |
| userID: Int      |  <--- This joins with the ID
| podcasterID: Int |       column of the user table.
| from: Date       |
| to: Date         |
| price: Float     |
+------------------+
#+END_EXAMPLE

-----

** Tasks:
1. /[[#foot][Feed]]/.
2. Audio player.
3. Playlists.
4. /[[#foot][XML Parser]]/.
5. Donations.
6. Slur-filter.
7. Spam-filter.
8. Keyboard navigation.
9. Get started/usage guide/documentation.

** Footnotes:
:PROPERTIES:
:CUSTOM_ID: foot
:END:
- Feed: A discoverable interface that presents a curated list of podcasts that constantly evolves per the *user's preferences*.
- XML Parser: RSS is at the backbone of the podcasting industry; RSS speaks XML. Magnum may retrieve and play *outside podcasts*, i.e. podcasts that are not available directly on the platform.
